model: "noam"
weight_tying: True

compile: True
grad_clip: 1.0
save_checkpoint_freq: 500
wandb_project: "lauzhack-llm"
wandb_group: "new"
wandb: True
n_layer: 12
opt: "adamw"
weight_decay: 0.1
lr: 1.e-4
#rho: 0.05
run_prefix: "new_large"

iterations: 12000 ## train itr: 958 ms, 3 hours of training => num iterations = (1/0.958)*3*60*60 = 11273
batch_size: 64
acc_steps: 4
