model: "noam"
weight_tying: True

compile: True
grad_clip: 1.0
save_checkpoint_freq: 500
wandb_project: "lauzhack-llm"
wandb_group: "new"
wandb: True
n_layer: 14
opt: "adamw"
weight_decay: 0.1
lr: 1.e-4
#rho: 0.05
run_prefix: "new_xl"

iterations: 11000 ## train itr: 1087 ms, 3 hours of training => num iterations = (1/1.087)*3*60*60 = 9935
batch_size: 64
acc_steps: 4
